#!/bin/bash

cd /srv/home/www

. /usr/local/deploy_hook.f

activate_pyvenv

WSGI_FILE="undefined"

function procfile_entry {
  NAME="$1"
  if [[ "$NAME" = "web" ]]; then
    CMD="$2"
    f=""
    if [ -f "$CMD" ]; then
      f="$CMD"
    fi
    if [[ $CMD =~ ^uwsgi\s+(\S+) ]]; then
      f="${BASH_REMATCH[1]}"
    fi
    WSGI_FILE="$f"
  fi
}

. /usr/local/procfile_to_supervisor


if [ "$WSGI_FILE" = "undefined" ]; then
  for f in wsgi.py index.py app.py run.py ; do
    if [ -f "$f" ]; then
      WSGI_FILE="$f"
      break
    fi
  done
fi

if [ "$COMMAND" = "undefined" ]; then
  echo "Cannot find app to start."
  exit 1
fi

exec uwsgi --plugin python35,http --master --virtualenv /srv/home/pyvenv --processes=5 --thunder-lock --socket :3000 --wsgi-file "$WSGI_FILE"
