#!/bin/bash

cd /srv/home/www

. /usr/local/deploy_hook.f

activate_pyvenv

WSGI_SWITCH="--wsgi-file"
WSGI_FILE="undefined"
WSGI_OPTS=()

function procfile_entry {
  NAME="$1"
  if [[ "$NAME" = "web" ]]; then
    eval set -- "$2"
    while [ $# -ge 1 ]; do
      case "$1" in
        --module)
          WSGI_SWITCH="--module"
          WSGI_FILE="$2"
          shift
          ;;
        --wsgi-file)
          WSGI_SWITCH="--wsgi-file"
          WSGI_FILE="$2"
          shift
          ;;
        --static-map)
          WSGI_OPTS+=('--static-map')
          WSGI_OPTS+=("$2")
          shift
          ;;
        *)
          # just ignore everythign else
          ;;
      esac

      shift
    done
  fi
  #skip, do not generate entry
  return 0
}
function procfiles_clean {
  return 0
}

. /usr/local/procfile_to_supervisor
procfile_process

if [ "$WSGI_FILE" = "undefined" ]; then
  for f in wsgi.py index.py app.py run.py ; do
    if [ -f "$f" ]; then
      WSGI_FILE="$f"
      break
    fi
  done
fi

if [ "$COMMAND" = "undefined" ]; then
  echo "Cannot find app to start."
  exit 1
fi

PROXY_TYPE=$( . /srv/home/.hostcfg && echo $PROXY_TYPE )
UWSGI_SOCKET_OPTION="--http-socket"
if [ "$PROXY_TYPE" = "uwsgi" ]; then
  UWSGI_SOCKET_OPTION="--socket"
fi

. /usr/local/start_app_hook.f
start_app_preexecute

exec uwsgi --chdir /srv/home/www --plugin python35,http --master --max-requests=5000 --virtualenv /srv/home/pyvenv --processes=5 --die-on-term --thunder-lock "$UWSGI_SOCKET_OPTION" :3000 "${WSGI_OPTS[@]}" "$WSGI_SWITCH" "$WSGI_FILE"
