#!/bin/bash

if [ -r Procfile ]; then
  rm -f /run/supervisor.d/Procfile_*.conf
  mkdir -p /run/supervisor.d/
  while IFS='' read -r line || [[ -n "$line" ]]; do
      if [[ $line =~ ^([a-zA-Z0-9]+):(.*)$ ]]; then
          NAME="${BASH_REMATCH[1]}"
          CMD="${BASH_REMATCH[2]}"
          printf "[program:${NAME}\ncommand=${CMD}\n" > "/run/supervisor.d/Procfile_${NAME}.conf"
      fi
  done < Procfile
fi
