#!/bin/sh

LOCK_FILE=/srv/home/www/persistent/.db_initialized
echo "=== Begin django database init `date -Iseconds` ==="

cd /srv/home/www/
if [ -f "${LOCK_FILE}" ]; then
  echo "=== Database exist, doing migrate"

  pyenv python3 manage.py migrate --noinput

else
  echo "=== Database initialization"

  pyenv python3 manage.py migrate --noinput
  pyenv python3 manage.py loaddata init
  echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@foggly.net', 'foggly-admin')" | pyenv python3 manage.py shell

fi
echo "=== Begin django database init `date -Iseconds` ==="

touch "${LOCK_FILE}"
