#!/bin/bash

if [[ "$GIT_DIR" ]]; then
    cd ..
    # don't mess up following git invocations
    unset GIT_DIR
fi

# Supress annoying perl messages about the locale
[[ -z "$LANG" ]] && export LANG=C
[[ -z "$LANGUAGE" ]] && export LANGUAGE=C
[[ -z "$LC_ALL" ]] && export LC_ALL=C
[[ -z "$LC_CTYPE" ]] && export LC_CTYPE=C

# Set ssh command that ignores hostchecks
export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

if [[ -f .gitmodules ]]; then
  # Handle git submodules
  echo "Process git submodule in `pwd`"
  git submodule  init
  git submodule  update
fi

. /usr/local/deploy_hook.f

deploy_hook_init

deploy_hook_install

if [ -x .hooks/on_deploy ]; then
  echo '*** BEGIN on_deploy in '`pwd`
  .hooks/on_deploy
  echo '*** END on_deploy'
fi

echo '*** BEGIN generate supervisor entries'
. /usr/local/procfile_to_supervisor
procfile_process

/usr/bin/supervisorctl reread
/usr/bin/supervisorctl update
echo '*** END generate supervisor entries'

deploy_hook_reload

exit 0
