#!/bin/bash

KEY_DIR=/srv/home/www/persistent/opendkim/keys
echo "=== Begin opendkim keys generation `date -Iseconds` ==="

DOMAIN=`hostname -f`
mkdir -p "$KEY_DIR"
cd "$KEY_DIR"
if [[ ! \( -f "${DOMAIN}.private" -a -f "${DOMAIN}.txt" \) ]]; then
  opendkim-genkey -s fogglymail -d "{$DOMAIN}"
  mv fogglymail.private "${DOMAIN}.private"
  mv fogglymail.txt "${DOMAIN}.txt"
fi
echo "=== End opendkim keys generation `date -Iseconds` ==="
