#!/bin/bash

if [[ "${REDIS_HOST}" =~ ^([0-9.]+)(:[0-9]+)?$ ]]; then
  REDIS_HOST="[${BASH_REMATCH[1]}]${BASH_REMATCH[2]:-:6379}"
elif [[ ! "${REDIS_HOST}" =~ ^:[0-9]+?$ ]]; then
  REDIS_HOST="${REDIS_HOST}:6379"
fi

exec /usr/bin/spiped -F -e -s [127.0.0.1]:6379 -t ${REDIS_HOST} -k /srv/home/www/persistent/redis-spiped.key
