#!/bin/bash

cd "${ROOT_DIR}/www/${WWW_ROOT_SUBDIR}"

CMD="undefined"

if [[ -f package.json ]]; then
  CMD=$(node -e 'fs=require("fs"); a = JSON.parse(fs.readFileSync("package.json")); console.log(a.scripts ? a.scripts.start: undefined)' )
fi

if [[ "$CMD" = "undefined" ]]; then
  for f in index.js app.js run.js; do
    if [[ -f "$f" ]]; then
      CMD="node $f"
      break
    fi
  done
fi

if [[ "$CMD" = "undefined" ]]; then
echo "Cannot find app to start."
exit 1
fi

export NODE_ENV='production'
exec $CMD
