#!/bin/bash

if [[ -z "$WORKER_QUEUE" ]]; then
  HOST_WORKER_QUEUE=`hostname -f`
fi
if [[ -z "$WORKER_QUEUE" ]]; then
  HOST_WORKER_QUEUE=`hostname`
fi

export HOST_WORKER_QUEUE
echo "Running worker for queue: $HOST_WORKER_QUEUE"
exec celery worker --loglevel=info --queues "$HOST_WORKER_QUEUE,any_host,every_host" --heartbeat-interval=15 
