# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 15:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160214_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('main_domain', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('controller_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('docker_port', models.IntegerField(default=2375, validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='domainmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shareddatabase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainmodel',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Host'),
        ),
        migrations.AddField(
            model_name='shareddatabase',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Host'),
        ),
    ]
