# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160311_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=8192)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DomainModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
