# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_domainconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercontainer',
            name='container_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dockercontainer',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
