# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160707_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='controller_ip',
        ),
        migrations.RemoveField(
            model_name='host',
            name='docker_port',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ip',
        ),
    ]
