# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160707_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DockerImage',
        ),
    ]
